class StringConsts {
  static StringConsts instance = StringConsts._init();

  StringConsts._init();

  final String logIn = "Log In";
  final String phoneNumber = "Phone Number";
  final String continueText = "Continue";
  final String verify = "Verify";
  final String orText = "Or";
  final String dontHaveAnAccount = "Don’t have an account?";
  final String register = "Register";
  final String registration = "Registration";
  final String personalInfo = "Personal info";
  final String sponsors = "Sponsors";
  final String myDashboard = "My dashboard";
  final String betterCoaching = "Better Coaching";
  final String myAvailability = "My availability";
  final String matches = "Matches";
  final String myPractice = "My practice";
  final String myStats = "My stats";
  final String clubExecutives = "Club Executives";
  final String payment = "Payment";
  final String clubDocuments = "Club documents";
  final String ramblers = "RAMBLERS";
  final String cricketInfo = "Cricket info";
  final String next = "Next";
  final String finish = "Finish";
  final String firstName = "First name";
  final String lastName = "Last name";
  final String gender = "Gender";
  final String dateOfBirth = "Date of birth ";
  final String email = "Email";
  final String phoneName = "Phone number";
  final String emergencyContactName = "Emergency contact name";
  final String emergencyContactNumber = "Emergency contact number";
  final String male = "Male";
  final String female = "Female";
  final String others = "Others";
  final String cricClubId = "CricClub ID";
  final String club = "Club";
  final String battingStyle = "Batting style";
  final String bowlingStyle = "Bowling style";
  final String fieldingPosition = "Fielding position";
  final String termsAndConditions = "Term and conditions";
  final String emptyStringMsg = "The field can't be empty";
  final String enterValidNumberMsg = "Please enter a valid mobile number";
  final String emailValidationMsg = "Enter a valid email address";
  final String emptyGenderMsg = "Gender field can't be empty";
  final String otpVerification = "OTP Verification";
  final String otpVerificationDesc = "OTP has sent to your registered phone number";
  final String selectUrAvailability = "Select your availability";
  final String selectUrAvailabilityDesc = "Please make sure your upcoming week availability before Tuesday.";
  final String available = "Available";
  final String notAvailable = "Not Available";
  final String upcomingWeek = "Upcoming week";
  final String pastDetails = "Past details";
  final String myProfile = "My Profile";
  final String paymentInfo = "Payment info";
  final String myPracticeSchedule = "My practice schedule";
  final String attendance = "Attendance";
  final String date = "Date";
  final String status = "Status";
  final String groundSchedules = "Ground schedules";
  final String selectUrAvailabilityForPractice = "Select your availability for practice";
  final String home = 'Home';
  final String eventsAndNews = 'Events & News';
  final String ecommerce = 'Ecommerce';
  final String profile = 'Profile';
  final String phone = 'Phone';
  final String address = 'Address';
  final String pending = 'Pending';
  final String completed = 'Completed';
  //new change
  final String clubMatchs = "Club Matches";
  final String myChedule = "My Schedule";
  final String myState = "My stats";
  final String clubExecutive = "Club Executives";

  // font family
  final String din800 = "assets/fonts/din_black.ttf";
  final String din700 = "assets/fonts/din_bold.ttf";
  final String din500 = "assets/fonts/din_medium.ttf";
  final String din400 = "assets/fonts/din_regular.ttf";
  final String eurostile = "assets/fonts/eurostile.ttf";
}
